"""Initial database schema for xiaoe_users

Revision ID: 61311ef0b4ed
Revises: 
Create Date: 2025-04-24 14:39:19.202390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61311ef0b4ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xiaoe_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('app_id', sa.String(length=255), nullable=True),
    sa.Column('union_id', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('created_at_platform', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xiaoe_users_app_id'), 'xiaoe_users', ['app_id'], unique=False)
    op.create_index(op.f('ix_xiaoe_users_id'), 'xiaoe_users', ['id'], unique=False)
    op.create_index(op.f('ix_xiaoe_users_phone'), 'xiaoe_users', ['phone'], unique=False)
    op.create_index(op.f('ix_xiaoe_users_union_id'), 'xiaoe_users', ['union_id'], unique=False)
    op.create_index(op.f('ix_xiaoe_users_user_id'), 'xiaoe_users', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xiaoe_users_user_id'), table_name='xiaoe_users')
    op.drop_index(op.f('ix_xiaoe_users_union_id'), table_name='xiaoe_users')
    op.drop_index(op.f('ix_xiaoe_users_phone'), table_name='xiaoe_users')
    op.drop_index(op.f('ix_xiaoe_users_id'), table_name='xiaoe_users')
    op.drop_index(op.f('ix_xiaoe_users_app_id'), table_name='xiaoe_users')
    op.drop_table('xiaoe_users')
    # ### end Alembic commands ###
