"""Allow null promoter in orders

Revision ID: d447589bdd24
Revises: 61311ef0b4ed
Create Date: 2025-04-25 13:40:29.557113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd447589bdd24'
down_revision: Union[str, None] = '61311ef0b4ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_xiaoe_users_app_id', table_name='xiaoe_users')
    op.drop_index('ix_xiaoe_users_id', table_name='xiaoe_users')
    op.drop_index('ix_xiaoe_users_phone', table_name='xiaoe_users')
    op.drop_index('ix_xiaoe_users_union_id', table_name='xiaoe_users')
    op.drop_index('ix_xiaoe_users_user_id', table_name='xiaoe_users')
    op.drop_table('xiaoe_users')
    op.alter_column('fact_xiaoe_order', 'promoter_user_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='推广员用户ID',
               existing_comment='推广员用户ID (外键)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fact_xiaoe_order', 'promoter_user_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='推广员用户ID (外键)',
               existing_comment='推广员用户ID',
               existing_nullable=True)
    op.create_table('xiaoe_users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('app_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('union_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('nickname', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('avatar_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024), nullable=True),
    sa.Column('gender', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('country', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('province', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('city', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('created_at_platform', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_xiaoe_users_user_id', 'xiaoe_users', ['user_id'], unique=True)
    op.create_index('ix_xiaoe_users_union_id', 'xiaoe_users', ['union_id'], unique=False)
    op.create_index('ix_xiaoe_users_phone', 'xiaoe_users', ['phone'], unique=False)
    op.create_index('ix_xiaoe_users_id', 'xiaoe_users', ['id'], unique=False)
    op.create_index('ix_xiaoe_users_app_id', 'xiaoe_users', ['app_id'], unique=False)
    # ### end Alembic commands ###
